server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    druid:
    #      url: jdbc:mysql://127.0.0.1:3306/vbox_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #      username: root
    #      password: root
    druid:
      url: jdbc:mysql://47.97.200.110:3306/vbox_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: vbox_admin
      password: Vbox123qwe
      # 初始化连接池 最小 最大
      initial-size: 10
      min-idle: 10
      max-active: 50
      # 获取连接池等待时间
      max-wait: 60000
      # 检测间隔，关闭空闲连接
      time-between-eviction-runs-millis: 60000
      # 连接最小生存时间
      min-evictable-idle-time-millis: 300000

  redis:
    # 正式
#    host: 39.98.203.241
    host: 127.0.0.1
    port: 6379
    password: Vbox123qwe
#    redisson: classpath:redisson.yml
#    host: 47.97.200.110

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
